### PR TITLE
feat: use more standardized release process.

### PR DESCRIPTION
**Pull request by mfrisbey**
## Description

Brings the library's release process more inline with `semantic-release`'s default settings. Releases will now be triggered with prefixes such as `feat:`, `fix:`, etc. In addition, release notes will automatically appear in `CHANGELOG.md`.

## Related Issue

N/A

## Motivation and Context

Provide better release notes and change log, avoid custom release triggering so that library-specific documentation and processes are reduced.

## How Has This Been Tested?

N/A

## Screenshots (if appropriate):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by tcallsen — CHANGES_REQUESTED** [review]
Looks good, but just some minor thoughts on the README:

- The formatting seems to have been skewed, and the table of contents was duplicated when viewing: https://github.com/adobe/cloud-service-client/tree/release-process
- It might be helpful to include the commit prefixes mentioned in the PR description directly in the release section; looking at the semantic release docs is not exactly straightfoward :-)

**Comment by mfrisbey** [comment]
@tcallsen whoa, good catch. I'm not sure how I missed that. I've removed the duplicate table of contents, and added some basic instructions for releasing.

**Review by tcallsen — APPROVED** [review]
Looks good! Fixed one additional indent issue in the `README` that was bothering me :-)

**Comment by mfrisbey** [comment]
@tcallsen haha, thanks for the fix!

**Pull request merged**
